name: product-classification
services:
  api:
    container_name: api
    image: joff15/e-commerce-mlops-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: backend/backend.Dockerfile
      target: ${TARGET?Variable not set}

    ports:
      - "8000:8000"

    env_file:
      - scripts/demo.env

    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}

    volumes:
      - ${DATA_VOLUME_SRC?Variable not set}:/backend/data:default
      # - products-data:${DATA_DIR?Variable not set}

  db:
    container_name: db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

    env_file:
      - scripts/demo.env

    ports:
      - "5432:5432"

  datascience:
    container_name: datascience
    image: joff15/e-commerce-mlops-datascience
    restart: unless-stopped
    build:
      context: .
      dockerfile: datascience/datascience.Dockerfile
      target: ${TARGET?Variable not set}

    ports:
      - "5010:5000"
      - "5011:5002"

    env_file:
      - scripts/demo.env

    volumes:
      - ${DATA_VOLUME_SRC?Variable not set}:/datascience/data:default
      # - products-data:${DATA_DIR?Variable not set}

volumes:
  postgres-data:
  products-data:

networks:
  default:
    name: product-classification
