default_install_hook_types: [pre-push, pre-commit]
repos:
-   repo: local
    hooks:
    -   id: code-checking
        stages: [pre-push, pre-commit]
        files: ^backend/
        types: [file, python]
        name: code-checking
        entry: ./backend/scripts/lint.sh
        language: system
        pass_filenames: false
        always_run: false
    -   id: pytest-check
        stages: [pre-push, pre-commit]
        files: ^backend/
        types: [file, python]
        name: pytest-check
        entry: ./backend/scripts/start-tests.sh
        language: system
        pass_filenames: false
        always_run: false
