name: Generate Poetry packages cache
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/poetry.lock"

jobs:
  project_matrix:
    strategy:
      matrix:
        project: [backend, datascience]
    name: ${{ matrix.project }} packages cache
    runs-on: ubuntu-latest
    environment: development
    steps:

    - name: Checkout repository code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      id: setup-python
      with:
        python-version: '3.11'

    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true

    - uses: actions/cache@v3
      name: Define a cache for the virtual environment based on the dependencies lock file
      with:
        path: ${{ matrix.project }}/.venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles(format('{0}/poetry.lock', matrix.project )) }}

    - name: Install the project dependencies
      run: poetry install --no-root --no-directory
      working-directory: ${{ matrix.project }}
