name: "Backend: debug of automated tests"
on:
  workflow_dispatch:
  push:
  pull_request:
    paths:
    - "backend/**"

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    environment: development
    env:
      working-directory: ./datascience
      
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      id: setup-python
      with:
        python-version: '3.11'

    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true

    - uses: actions/cache@v3
      name: Define a cache for the virtual environment based on the dependencies lock file
      with:
        path: ${{env.working-directory}}/.venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles(format('{0}/poetry.lock', env.working-directory )) }}

    - name: Install the project dependencies
      run: poetry install --no-root --no-directory
      working-directory: ${{env.working-directory}}
      
    - name: Deploy project with staging configuration and run tests
      if: always()
      run: scripts/run-tests-in-containers.sh
      
