name: Linter and unit tests
on: 
  workflow_dispatch:
  pull_request:

jobs:
  container-job:
    name: Run linting and unit tests
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_SERVER: db
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: changethis
          POSTGRES_DB: product-classification
        ports:
          - 5432:5432

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Dotenv Action
      uses: falti/dotenv-action@v1.0.4
      with:
        export-variables: true
        keys-case: bypass

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: "**/requirements*.txt"
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=./" >> "$GITHUB_ENV"
      working-directory: ./backend

    - name: Cache pip packages
      uses: actions/cache@v3.2.4
      id: cache
      with:
        path: ${{ env.pythonLocation }}
        # Editing one of the requirements file triggers a cache refresh
        key: ${{ env.pythonLocation }}-${{ hashFiles('./backend/requirements.txt') }}-${{ hashFiles('./backend/requirements-dev.txt') }}
    - name: Install pip packages
      if: steps.cache.outputs.cache-hit != 'true'
      run: pip install -r ./backend/requirements.txt -r ./backend/requirements-dev.txt

    - name: Cache saved models
      uses: actions/cache@v3.2.4
      id: cache-models
      with:
        path: ./backend/datascience/data
        # Editing the script to download the model saves triggers a cache refresh
        key: -${{ hashFiles('./backend/scripts/download_models.py') }}
    - name: Download saved models
      if: steps.cache-models.outputs.cache-hit != 'true'
      run: python scripts/download_models.py 
      working-directory: ./backend

    - name: Run linter
      working-directory: ./backend
      if: always()
      run: ./scripts/lint.sh

    - name: Run unit tests
      working-directory: ./backend
      if: always()
      run: ./scripts/start-tests.sh
      env:
        POSTGRES_SERVER: localhost
